name: Auto Sync

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          upstream_repository: https://github.com/vuejs/pinia
          upstream_branch: v2
          target_repository: https://github.com/niceplugin/Vuejs-Pinia-KO
          target_branch: v2
